@extends('layouts.front')
@section('intro')
    @include('home.intro')
@stop
@section('tips')
    @include('home.tips')
@stop
@section('ingredients')
    @include('home.ingredients')
@stop
@section('shop')
    @include('home.shop')
@stop