ALTER SEQUENCE ordini_dettaglio_id_seq RESTART WITH 7000;
ALTER SEQUENCE ordini_testa_id_seq RESTART WITH 15000;
ALTER SEQUENCE ordini_stato_id_seq RESTART WITH 6000;
ALTER SEQUENCE ordini_vettura_id_seq RESTART WITH 4000;
ALTER SEQUENCE utenti_id_seq RESTART WITH 5000;
ALTER SEQUENCE clienti_id_seq RESTART WITH 7000;